apiVersion: v1
kind: Pod
metadata:
  name: javaweb-2
spec:
  initContainers:
    - image: geektime/sample:v2
      name: war
      command: [ "cp","/sample.war","/app" ]
      volumeMounts:
        - name: app-volume
          mountPath: /app
  containers:
    - image: geektime/tomcat:7.0
      name: tomcat
      command: [ "sh","-c","/root/apache-tomcat-7.0.42-v2/bin/start.sh" ]
      volumeMounts:
        - name: app-volume
          mountPath: /root/apache-tomcat-7.0.42-v2/webapps
      ports:
        - containerPort: 8080
          hostPort: 8001
  volumes:
    - name: app-volume
      emptyDir: { }