apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-database
spec:
  selector:
    matchLabels:
      role: frontend
  env:
    - name: DB_PORT
      value: "3306"
  volumeMounts:
    - name: db-volume
      mountPath: /var/lib/mysql
  volumes:
    - name: db-volume
      emptyDir: { }