apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  shareProcessNamespace: true
  containers:
    - name: nginx
      image: nginx:1.15.8
    - name: shell
      image: busybox
      stdin: true
      tty: true

